# -*- coding: utf-8 -*-
"""BIO_PROJECT.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wqLDr8KyNQU4pmVmNso86N_nLGGYwbZ7

Import
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
# %matplotlib inline

"""Traitement des données"""

data = pd.read_csv("/survey lung cancer.csv")
data.head()

sns.countplot(x='LUNG_CANCER',hue='LUNG_CANCER',data=data)

find_duplicate = data[data.duplicated()].shape[0]
data.drop_duplicates(keep='first',inplace=True)

data_lung_only= data[data['LUNG_CANCER']=='YES']
data_lung_only.head()

plt.figure(figsize=(20,10))
sns.kdeplot(data_lung_only["AGE"],color='black')

plt.figure(figsize=(20,10))
sns.histplot(data_lung_only[data_lung_only['GENDER']=='F']['AGE'],kde=True,color='red')
plt.title("Age vs Count for Female")

sns.catplot('SMOKING',kind='count',data=data_lung_only,palette='BuGn',order=[1,2]).set_xticklabels(['Non Fumeur','Fumeur'])

sns.catplot('GENDER',data=data_lung_only,kind='count',palette='BuGn').set(title='Comparaison Hommes/Femmes').set_xticklabels(['Femme','Homme'])

Label= LabelEncoder()
data['LUNG_CANCER']= Label.fit_transform(data['LUNG_CANCER'])

data['GENDER']=Label.fit_transform(data['GENDER'])
data.head()

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(data.drop('LUNG_CANCER',axis=1),data['LUNG_CANCER'],test_size=0.3)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
model = LogisticRegression()
model.fit(X_train,y_train)
predictions = model.predict(X_test)
plt.scatter(y_test, predictions)
plt.hist(y_test - predictions)

print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))
